/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArxivRouteImport } from './routes/arxiv'
import { Route as ElementyRouteImport } from './routes/elementy'
import { Route as EscheRouteImport } from './routes/esche'
import { Route as RaschetRouteImport } from './routes/raschet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArxivRoute = ArxivRouteImport.update({
  id: '/arxiv',
  path: '/arxiv',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementyRoute = ElementyRouteImport.update({
  id: '/elementy',
  path: '/elementy',
  getParentRoute: () => rootRouteImport,
} as any)
const EscheRoute = EscheRouteImport.update({
  id: '/esche',
  path: '/esche',
  getParentRoute: () => rootRouteImport,
} as any)
const RaschetRoute = RaschetRouteImport.update({
  id: '/raschet',
  path: '/raschet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arxiv': typeof ArxivRoute
  '/elementy': typeof ElementyRoute
  '/esche': typeof EscheRoute
  '/raschet': typeof RaschetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arxiv': typeof ArxivRoute
  '/elementy': typeof ElementyRoute
  '/esche': typeof EscheRoute
  '/raschet': typeof RaschetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arxiv': typeof ArxivRoute
  '/elementy': typeof ElementyRoute
  '/esche': typeof EscheRoute
  '/raschet': typeof RaschetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arxiv' | '/elementy' | '/esche' | '/raschet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arxiv' | '/elementy' | '/esche' | '/raschet'
  id: '__root__' | '/' | '/arxiv' | '/elementy' | '/esche' | '/raschet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArxivRoute: typeof ArxivRoute
  ElementyRoute: typeof ElementyRoute
  EscheRoute: typeof EscheRoute
  RaschetRoute: typeof RaschetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arxiv': {
      id: '/arxiv'
      path: '/arxiv'
      fullPath: '/arxiv'
      preLoaderRoute: typeof ArxivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementy': {
      id: '/elementy'
      path: '/elementy'
      fullPath: '/elementy'
      preLoaderRoute: typeof ElementyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esche': {
      id: '/esche'
      path: '/esche'
      fullPath: '/esche'
      preLoaderRoute: typeof EscheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raschet': {
      id: '/raschet'
      path: '/raschet'
      fullPath: '/raschet'
      preLoaderRoute: typeof RaschetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArxivRoute: ArxivRoute,
  ElementyRoute: ElementyRoute,
  EscheRoute: EscheRoute,
  RaschetRoute: RaschetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
